---
abstract: 'make a choice with the choose command line util'
author:
  - 'Written by Mark Fowler <mark@twoshortplanks.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mac-Choose
no_index:
  directory:
    - inc
    - t
requires:
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1
